Add monthCode for all userinfo files
fjcoding/AT17 pull request #74
Opened 2022-05-27 13:08 UTC by Renucopata

2022-05-29 19:50 UTC, moreHc requested changes

2022-05-29 19:50 UTC, moreHc commented on git-playground/pablo/userinfo
> +Pablo-07
Pablo's birthday month is 06, please fix

2022-05-30 13:22 UTC, moreHc requested changes
All lines are missing "month code:"

2022-05-31 02:55 UTC, J0c4 commented
Hi @Renucopata , please don't forget to follow up pending changes for this PR

2022-05-31 05:39 UTC, Renucopata commented
-Pablo's birthday month code fixed
-Add the word "month code: " to all user info files
-Add the rest of information on rene/userinfo file

2022-06-02 13:43 UTC, J0c4 approved these changes

2022-06-02 13:44 UTC, J0c4 commented
Changes look good.

@moreHc , since you requested changes (which is ok), PR needs your review/approval as well, please check and if everything looks ok, lets approve and merge

2022-06-02 13:50 UTC, moreHc approved these changes

2022-06-02 13:50 UTC, merged