Add hobbyinfo file for all students including music/movie code
fjcoding/AT17 pull request #80
Opened 2022-05-30 12:37 UTC by micakler

2022-05-30 13:57 UTC, J0c4 requested changes
Hi Micaela, please solve new merge conflicts reported

2022-05-30 15:29 UTC, MatiasVerdugo submitted a review, later dismissed
Everything seems fine

2022-05-31 00:05 UTC, MariaInesB7 approved these changes

2022-05-31 02:55 UTC, J0c4 requested changes

2022-05-31 02:55 UTC, J0c4 commented on git-playground/mariaines/hobbyinfo
> +movies count: 2
Looks like changes were duplicated here, maybe due conflict resolution? Please remove duplicated lines

2022-06-02 13:46 UTC, J0c4 approved these changes

2022-06-02 13:46 UTC, merged