Pull request to add Morelia/langtonant branch to dev/langtonant
fjcoding/AT17 pull request #84
Opened 2022-05-31 03:29 UTC by moreHc

2022-05-31 03:45 UTC, Rafasebass25 requested changes
Need to solve merge issues first

2022-05-31 03:45 UTC, Rafasebass25 approved these changes

2022-06-01 01:24 UTC, Rafasebass25 submitted a review, later dismissed

2022-06-03 04:03 UTC, J0c4 approved these changes

2022-06-03 04:03 UTC, J0c4 commented
Nice work!

2022-06-03 04:03 UTC, merged