Add rafael/langtonant to dev/langonant
fjcoding/AT17 pull request #88
Opened 2022-06-01 00:34 UTC by Rafasebass25

This a little advance. I am still working in the excercise

2022-06-01 01:28 UTC, moreHc submitted a review, later dismissed

2022-06-03 04:34 UTC, J0c4 requested changes
You have nice function names, and logic seems to be working fine. Lint issues need to be fixed and modules names

2022-06-03 04:34 UTC, J0c4 commented on katas/langtonant/rafael/module.js
> +import { ShowMatrix } from "./module1.js";
function names are good, module names should be improved

2022-06-03 04:34 UTC, J0c4 commented on katas/langtonant/rafael/module.js
> +    for(let i=0;i<extension;i++)
There are lint issues, please fix them

2022-06-03 04:35 UTC, J0c4 commented
Also, please don't forget to fix merge conflicts

2022-06-03 13:21 UTC, merged