ant passed by lint and fixed
fjcoding/AT17 pull request #94
Opened 2022-06-02 00:00 UTC by MatiasVerdugo

2022-06-03 05:00 UTC, J0c4 requested changes

2022-06-03 05:00 UTC, J0c4 commented on katas/langtonant/matias/main.test.js
> +import { Ant } from './main.js';
This is a good start. Please add more tests for verifying all the functionality you have here

2022-06-03 05:00 UTC, J0c4 commented on katas/langtonant/matias/main.js
> +class Ant {
Looks like implementation still in progress, please let me know if you are planning to push more changes to complete the Kata

2022-06-03 05:00 UTC, J0c4 commented
There are some failures when running test and lint, please check and fix them along with fixing merge conflicts

2022-06-06 19:41 UTC, J0c4 requested changes
Hi Matias, your implementation looks good. Few observations:
- You need to add more test for smaller pieces in your code, that way, you verify that smaller functions are verified in multiple scenarios
- I was not able to test it using the main file, did I miss something?

Also, apparently, there is a syntax error in the line 7 of main.js file that is detected by lint, that needs to be fixed before we merge this branch, please fix and we can merge this

2022-06-07 00:57 UTC, MatiasVerdugo commented
> Hi Matias, your implementation looks good. Few observations:
> 
> * You need to add more test for smaller pieces in your code, that way, you verify that smaller functions are verified in multiple scenarios
> * I was not able to test it using the main file, did I miss something?
> 
> Also, apparently, there is a syntax error in the line 7 of main.js file that is detected by lint, that needs to be fixed before we merge this branch, please fix and we can merge this

I've fixed the error on the line 7 updating the parser of lint, and the error was gone.

2022-06-08 00:31 UTC, J0c4 commented
> > Hi Matias, your implementation looks good. Few observations:
> > 
> > * You need to add more test for smaller pieces in your code, that way, you verify that smaller functions are verified in multiple scenarios
> > * I was not able to test it using the main file, did I miss something?
> > 
> > Also, apparently, there is a syntax error in the line 7 of main.js file that is detected by lint, that needs to be fixed before we merge this branch, please fix and we can merge this
> 
> I've fixed the error on the line 7 updating the parser of lint, and the error was gone.

Looks like issue still present, variable does not seem to be correctly declared

2022-06-10 00:46 UTC, J0c4 commented
Hi @MatiasVerdugo , any updates on this one? if lint issues do not get fixed, we cannot merge this as it will break the build status. Since its been a while for this PR, we will need to set tomorrow as a deadline so we can close it.

2022-06-10 01:07 UTC, MatiasVerdugo commented
> Hi @MatiasVerdugo , any updates on this one? if lint issues do not get fixed, we cannot merge this as it will break the build status. Since its been a while for this PR, we will need to set tomorrow as a deadline so we can close it.

I'm sorry for the delay is already updated

2022-06-10 01:12 UTC, MatiasVerdugo commented
> > Hi Matias, your implementation looks good. Few observations:
> > 
> > * You need to add more test for smaller pieces in your code, that way, you verify that smaller functions are verified in multiple scenarios
> > * I was not able to test it using the main file, did I miss something?
> > 
> > Also, apparently, there is a syntax error in the line 7 of main.js file that is detected by lint, that needs to be fixed before we merge this branch, please fix and we can merge this
> 
> I've fixed the error on the line 7 updating the parser of lint, and the error was gone.

"Unexpected token errors in ESLint parsing occur due to incompatibility between your development environment and ESLint's current parsing capabilities with the ongoing changes with JavaScripts ES6~7."

The solution is to have ESLint parsed by a compatible parser, i.e @babel/eslint-parser or babel-eslint for babel version below v7.

just add:

"parser": "@babel/eslint-parser"
to your .eslintrc file and run npm install @babel/eslint-parser --save-dev or yarn add -D @babel/eslint-parser.

2022-06-11 05:22 UTC, J0c4 commented
hi @MatiasVerdugo , unfortunately there is a missing change that is adding eslint-parser to package.json which is added by running the command npm install @babel/eslint-parser that you have in your comment. Without this, the configuration that you added will not work.

As mentioned, lets close this one for now without merging. We can follow up if you have questions about this topic

2022-06-11 05:22 UTC, closed without merging