Jorge/langtonant with Lint and Lint:fix and creation of jlangtonsant.test.js file
fjcoding/AT17 pull request #95
Opened 2022-06-02 04:30 UTC by jarmcode

In this PR there is my langtonsant code with lint and lint:fix and also the jlangtonsant.test.js file

2022-06-03 05:08 UTC, J0c4 requested changes
Implementation looks good, it seems to be working as expected. There are more tests that should be added for antWalk, moveForward, turnLeft, turnRight

2022-06-03 05:08 UTC, J0c4 commented on katas/langtonant/jorge/jlangtonsant.js
> +let ANTLEFT = 3;
These variables are ok, however, if used as constants, please define them with `const` instead

2022-06-03 05:08 UTC, J0c4 commented on katas/langtonant/richard/main.js
> -
I think this file should not be deleted

2022-06-03 05:08 UTC, J0c4 commented on katas/langtonant/richard/module1.js
> -
Richard did a refactor, but still, maybe this should not be removed to prevent merge conflicts

2022-06-03 05:08 UTC, J0c4 commented
Also, please solve merge conflicts

2022-06-06 19:45 UTC, J0c4 requested changes
Looks good!

Please rollback changes to `package-lock.json` file, this was probably modified when `npm install` was executed. We can ignore those changes for now

2022-06-08 00:33 UTC, J0c4 commented
> Looks good!
> 
> Please rollback changes to `package-lock.json` file, this was probably modified when `npm install` was executed. We can ignore those changes for now

Hi @jarmcode , still need this update to merge

2022-06-10 00:48 UTC, J0c4 commented
Hi @jarmcode , any updates on this one? issues need to be fixed because it might break the build. Since its been a while for this PR, we will need to set tomorrow as a deadline so we can close it

2022-06-10 02:35 UTC, jarmcode commented
hi, Jose!

Conflicts have been solved!

2022-06-11 05:26 UTC, J0c4 commented
Hi @jarmcode , unfortunately, looks like coverage/ folder has been added (this files are expected not to be added to the repo), so this would prevent the approval of this PR, along with the package-lock.json file that was not reverted.

As mentioned, lets close this one for now, but we can follow up in this topic in case you have questions.

2022-06-11 05:26 UTC, closed without merging