Add micaela/langtonant to dev/langtonant branch
fjcoding/AT17 pull request #97
Opened 2022-06-02 12:36 UTC by micakler

2022-06-02 13:37 UTC, micakler commented on katas/langtonant/micaela/functions.tests.js
> +
Isn´t finished

2022-06-02 13:37 UTC, micakler commented on katas/langtonant/micaela/functions.tests.js
> +
Isn´t finished

2022-06-03 05:22 UTC, J0c4 requested changes
Hi Micaela, looks like you have good progress here, but still need to complete the code to test everything and run main code, please include missing changes

2022-06-03 05:22 UTC, J0c4 commented on katas/langtonant/micaela/functions.tests.js
> +import { FuncMatrix, Movements } from './functions';
Looks like the tests are not being run because file name contains `tests` instead of `test`, please fix the file name so the tests can be run

2022-06-03 05:22 UTC, J0c4 commented on package.json
> +    "langtonant:micaela": "node katas/langtonant/micaela/main.js",
script is ok, but micaela/main.js is missing, still pending to be added?

2022-06-06 19:51 UTC, J0c4 requested changes
Hi @micakler , you have good progress here. Few things that need to be complete before merge:
- there are some lint issues, please fix them
- there is a conflict that needs to be solved, you can sync with @AlfredPereira and @guillav29 to see who will merge his PR first so you guys don't need to solve conflicts two or three times again.
- When I run main, there seems to be an error importing a dependency, maybe can be fixed if you add '.js' extension to the file referenced in the import

2022-06-08 00:39 UTC, J0c4 commented
Hi Micaela, thanks for the updates, there are couple that still need to be fixed:
- Error while running main.js
- please revert changes commited for package-lock.json file

2022-06-08 01:43 UTC, J0c4 commented
for reverting package-lock.json file, you can try this: https://dev.to/lofiandcode/git-and-github-how-to-revert-a-single-file-dha

2022-06-10 00:49 UTC, J0c4 commented
Hi @micakler , any updates on this one? if issues do not get fixed, we cannot merge this as it will break the build status. Since its been a while for this PR, we will need to set tomorrow as a deadline so we can close it

2022-06-10 16:37 UTC, micakler commented
I tried to revert package-lock.json file but i couldn't do it

2022-06-11 05:27 UTC, J0c4 commented
Ok, lets close this one for now. We can follow up in case you have further questions about this one.

2022-06-11 05:27 UTC, closed without merging