Add code of args task for merge into dev/args whit Christian/args
fjcoding/AT17 pull request #99
Opened 2022-06-06 02:29 UTC by clopezbaya

2022-06-06 19:55 UTC, J0c4 requested changes
Looks good, just few comments about english. Also, it would be good to have behavior implemented with schema as well (did I miss it?)

2022-06-08 00:41 UTC, J0c4 commented
Hello @clopezbaya , any updates on the changes requested? (use english instead of spanish in code). We need those changes in order to approve an merge this PR

2022-06-08 00:43 UTC, clopezbaya commented
Okay i am sorry , I forget now update please

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Jose Carlos ***@***.***>
Sent: Tuesday, June 7, 2022 8:41:54 PM
To: fjcoding/AT17 ***@***.***>
Cc: Christian Lopez Baya ***@***.***>; Mention ***@***.***>
Subject: Re: [fjcoding/AT17] Add code of args task for merge into dev/args whit Christian/args (PR #99)


Hello @clopezbaya<https://github.com/clopezbaya> , any updates on the changes requested? (use english instead of spanish in code). We need those changes in order to approve an merge this PR

—
Reply to this email directly, view it on GitHub<https://github.com/fjcoding/AT17/pull/99#issuecomment-1149319413>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AMFQP7GXHLHB5Y7RBTBY5D3VN7T5FANCNFSM5X57YJ2Q>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-06-08 01:26 UTC, clopezbaya commented on katas/args/christian/parserClass.test.js
> +    expect(result).toBe('Ningun Argumento Coincide');
All the problems are already solved

2022-06-08 01:27 UTC, clopezbaya commented on katas/args/christian/main.js
> +process.stdout.write('ingresa los argumentos: ');
All the problems are already solved

2022-06-08 02:34 UTC, J0c4 commented
hi @clopezbaya , just noticed, I detect some copy paste here, who is the real author?

2022-06-08 02:38 UTC, clopezbaya commented
Yes I am the owner of the code, I made it from scratch

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Jose Carlos ***@***.***>
Sent: Tuesday, June 7, 2022 10:34:31 PM
To: fjcoding/AT17 ***@***.***>
Cc: Christian Lopez Baya ***@***.***>; Mention ***@***.***>
Subject: Re: [fjcoding/AT17] Add code of args task for merge into dev/args whit Christian/args (PR #99)


hi @clopezbaya<https://github.com/clopezbaya> , just noticed, I detect some copy paste here, who is the real author?

—
Reply to this email directly, view it on GitHub<https://github.com/fjcoding/AT17/pull/99#issuecomment-1149386839>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AMFQP7BMK2K7HHCG6BJTS6TVOABDPANCNFSM5X57YJ2Q>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-06-08 02:42 UTC, J0c4 approved these changes

2022-06-08 02:42 UTC, merged